'use client';
import {useHydrated} from '@/hooks/useHydrated';
import Link from 'next/link';
import Image from 'next/image';
import {Minus,Plus,Trash2,ArrowLeft} from 'lucide-react';
import {useCartStore} from '@/store/cart';
import {formatPrice} from '@/lib/utils';
export default function Cart(){const ready=useHydrated();const {items,removeItem,updateQuantity,getTotalPrice}=useCartStore();if(!ready)return <div className="container py-20" role="status">Carregando sua sacola...</div>;return <div className="container py-12 lg:py-16"><p className="eyebrow">Suas escolhas</p><h1 className="text-4xl lg:text-5xl mb-10">Minha sacola.</h1>{!items.length?<div className="bg-gray-50 text-center p-12"><h2 className="text-2xl mb-4">O próximo favorito está por aí.</h2><p className="text-gray-500 mb-8">Explore o catálogo e encontre peças com a sua cara.</p><Link href="/busca" className="btn-primary">Explorar a loja</Link></div>:<div className="grid lg:grid-cols-[1fr_350px] gap-10"><div>{items.map(i=><article key={i.product.id+i.selectedSize+i.selectedColor} className="border-t py-6 flex gap-5"><Link href={'/produto/'+i.product.slug}><Image src={i.product.images[0]} alt={i.product.name} width={128} height={171} className="w-24 sm:w-32 aspect-[3/4] object-cover"/></Link><div className="flex-1"><h2 className="text-sm sm:text-base mb-2"><Link href={'/produto/'+i.product.slug}>{i.product.name}</Link></h2><p className="text-xs text-gray-500 mb-5">{i.selectedSize} / {i.selectedColor}</p><div className="flex flex-wrap gap-5 justify-between items-center"><div className="border flex items-center"><button className="p-3" aria-label="Diminuir quantidade" onClick={()=>updateQuantity(i.product.id,i.selectedSize,i.selectedColor,i.quantity-1)}><Minus size={14}/></button><span className="text-sm px-3">{i.quantity}</span><button className="p-3" aria-label="Aumentar quantidade" onClick={()=>updateQuantity(i.product.id,i.selectedSize,i.selectedColor,i.quantity+1)}><Plus size={14}/></button></div><strong>{formatPrice(i.product.price*i.quantity)}</strong></div></div><button className="self-start p-2" aria-label={'Remover '+i.product.name} onClick={()=>removeItem(i.product.id,i.selectedSize,i.selectedColor)}><Trash2 size={16}/></button></article>)}<Link href="/busca" className="text-link mt-5"><ArrowLeft size={16}/>Continuar explorando</Link></div><aside className="bg-gray-50 p-7 self-start"><h2 className="text-xl mb-7">Resumo</h2><div className="flex justify-between mb-6"><span>Subtotal</span><strong>{formatPrice(getTotalPrice())}</strong></div><p className="text-sm text-gray-500 mb-7">Frete e condições de pagamento serão informados antes da conclusão da compra.</p><Link className="btn-primary w-full text-sm" href="/checkout">Continuar</Link></aside></div>}</div>;}

