begin;
create table if not exists public.site_sections (id uuid primary key default gen_random_uuid(), key text unique not null, page_path text not null default '/', kind text not null check(kind in ('hero','artists','products','campaign','categories','benefits','community','text','announcement','footer')), title text not null default '', eyebrow text not null default '', description text not null default '', image text not null default '', mobile_image text not null default '', alt text not null default '', button_text text not null default '', link text not null default '', video_url text not null default '', theme text not null default 'dark' check(theme in ('light','dark')), position integer not null default 0 check(position>=0), is_active boolean not null default false, items jsonb not null default '[]' check(jsonb_typeof(items)='array'), updated_at timestamptz not null default now());
alter table public.site_sections enable row level security;
create policy sections_public_read on public.site_sections for select using(is_active or public.is_admin());
create policy sections_admin on public.site_sections for all using(public.is_admin()) with check(public.is_admin());
grant select on public.site_sections to anon,authenticated;
grant insert,update,delete on public.site_sections to authenticated;
create trigger sections_updated before update on public.site_sections for each row execute function public.set_updated_at();
create index sections_page_order on public.site_sections(page_path,position);
insert into public.creators(name,slug) values('MC POZE DO RODO','mc-poze-do-rodo') on conflict(slug) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('hero','hero','Moda que vem da realidade.',10,'/','','','','','','','','','dark',true,'[{"title":"MODA QUE\nVEM DA\nREALIDADE.","image":"/images/street-editorial.webp","link":"/lancamentos","description":"Roupa, cultura e atitude. Exclusivos de artistas do rap e funk.","reference":"","mobile_image":"","alt":"MODA QUE\nVEM DA\nREALIDADE.","button_text":"Ver lançamentos","eyebrow":"CULTURA · MÚSICA · ATITUDE"},{"title":"MAIS QUE\nROUPA,\nÉ CULTURA.","image":"/images/campaign.webp","link":"/colecoes","description":"Coleções que carregam histórias. Da rua pro mundo.","reference":"","mobile_image":"","alt":"MAIS QUE\nROUPA,\nÉ CULTURA.","button_text":"Explorar coleções","eyebrow":"COLEÇÕES OFICIAIS"},{"title":"VISTA\nO QUE\nTE MOVE.","image":"/images/street-editorial.webp","link":"/artistas","description":"Conexão real com quem faz história.","reference":"","mobile_image":"","alt":"VISTA\nO QUE\nTE MOVE.","button_text":"Conhecer artistas","eyebrow":"ARTISTAS DRIPSHOP"}]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('artists','artists','VOZES QUE
VESTEM CULTURA.',20,'/','ARTISTAS','Mais que roupas. Conexão real com quem faz história.','','','','Ver todos os artistas','/artistas','','dark',true,'[{"title":"TZ DA CORONEL","image":"","link":"/artista/tz-da-coronel","description":"","reference":"tz-da-coronel","mobile_image":"","alt":"TZ DA CORONEL","button_text":"Ver coleção","eyebrow":""},{"title":"MC LAN","image":"","link":"/artista/mc-lan","description":"","reference":"mc-lan","mobile_image":"","alt":"MC LAN","button_text":"Ver coleção","eyebrow":""},{"title":"MC POZE DO RODO","image":"","link":"/artista/mc-poze-do-rodo","description":"","reference":"mc-poze-do-rodo","mobile_image":"","alt":"MC POZE DO RODO","button_text":"Ver coleção","eyebrow":""},{"title":"OUTROS ARTISTAS","image":"/images/campaign.webp","link":"/artistas","description":"","reference":"","mobile_image":"","alt":"OUTROS ARTISTAS","button_text":"Ver coleção","eyebrow":""}]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('launches','products','LANÇAMENTOS',30,'/','','Do estúdio pra sua rua.','','','','Ver todos','/lancamentos','','light',true,'[]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('collections','campaign','MAIS QUE ROUPA.
É CULTURA.',40,'/','COLEÇÕES OFICIAIS','Histórias, vivências e a força da cultura de rua brasileira.','/images/street-editorial.webp','','Campanha editorial DripShop em arquitetura urbana','Explorar coleções','/colecoes','','dark',true,'[]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('categories','categories','CATEGORIAS',50,'/','','Encontre seu estilo.','','','','Ver todas','/busca','','light',true,'[{"title":"CAMISETAS","image":"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85","link":"/categoria/camisetas","description":"","reference":"","mobile_image":"","alt":"CAMISETAS","button_text":"Ver coleção","eyebrow":""},{"title":"MOLETONS","image":"https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=85","link":"/categoria/moletom","description":"","reference":"","mobile_image":"","alt":"MOLETONS","button_text":"Ver coleção","eyebrow":""},{"title":"BONÉS","image":"","link":"/busca?q=bon%C3%A9","description":"","reference":"","mobile_image":"","alt":"BONÉS","button_text":"Ver coleção","eyebrow":""},{"title":"ACESSÓRIOS","image":"","link":"/categoria/acessorios","description":"","reference":"","mobile_image":"","alt":"ACESSÓRIOS","button_text":"Ver coleção","eyebrow":""},{"title":"CALÇAS","image":"","link":"/busca?q=cal%C3%A7a","description":"","reference":"","mobile_image":"","alt":"CALÇAS","button_text":"Ver coleção","eyebrow":""},{"title":"OUTLET","image":"/images/campaign.webp","link":"/promocao","description":"","reference":"","mobile_image":"","alt":"OUTLET","button_text":"Ver coleção","eyebrow":""}]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('benefits','benefits','Vantagens DripShop',60,'/','','','','','','','','','dark',true,'[{"title":"PRODUTOS OFICIAIS","image":"","link":"","description":"Direto da cena","reference":"","mobile_image":"","alt":"PRODUTOS OFICIAIS","button_text":"Ver coleção","eyebrow":""},{"title":"ENTREGA NACIONAL","image":"","link":"","description":"Da rua pro Brasil inteiro","reference":"","mobile_image":"","alt":"ENTREGA NACIONAL","button_text":"Ver coleção","eyebrow":""},{"title":"TROCA FÁCIL","image":"","link":"/p/trocas","description":"Conheça nossa política","reference":"","mobile_image":"","alt":"TROCA FÁCIL","button_text":"Ver coleção","eyebrow":""},{"title":"ATENDIMENTO","image":"","link":"/p/fale-conosco","description":"Conte com a gente","reference":"","mobile_image":"","alt":"ATENDIMENTO","button_text":"Ver coleção","eyebrow":""}]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('community','community','RECEBA NOVIDADES EXCLUSIVAS.',70,'/','COMUNIDADE DRIPSHOP','Lançamentos, coleções e conteúdos da cena no seu e-mail.','/images/campaign.webp','','Campanha de streetwear DripShop','Inscrever-se','','','light',true,'[{"title":"DRIPSHOP NA RUA","image":"","link":"/p/sobre-nos","description":"Moda, música e realidade. Conheça o que nos move.","reference":"","mobile_image":"","alt":"DRIPSHOP NA RUA","button_text":"Ver coleção","eyebrow":""}]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('announcement','announcement','PRODUTOS OFICIAIS E EXCLUSIVOS',0,'/global','','','','','','','','','dark',true,'[{"title":"PRODUTOS OFICIAIS E EXCLUSIVOS","image":"","link":"","description":"","reference":"","mobile_image":"","alt":"PRODUTOS OFICIAIS E EXCLUSIVOS","button_text":"Ver coleção","eyebrow":""},{"title":"DA RUA PRO MUNDO.","image":"","link":"","description":"","reference":"","mobile_image":"","alt":"DA RUA PRO MUNDO.","button_text":"Ver coleção","eyebrow":""},{"title":"TROCA FÁCIL","image":"","link":"/p/trocas","description":"","reference":"","mobile_image":"","alt":"TROCA FÁCIL","button_text":"Ver coleção","eyebrow":""}]') on conflict(key) do nothing;
insert into public.site_sections(key,kind,title,position,page_path,eyebrow,description,image,mobile_image,alt,button_text,link,video_url,theme,is_active,items) values('footer','footer','DA RUA PRO MUNDO.',100,'/global','','Moda, música e expressão.
Do Brasil para o mundo.','','','','','','','dark',true,'[{"title":"Novidades","image":"","link":"/lancamentos","description":"","reference":"Loja","mobile_image":"","alt":"Novidades","button_text":"Ver coleção","eyebrow":""},{"title":"Artistas","image":"","link":"/artistas","description":"","reference":"Loja","mobile_image":"","alt":"Artistas","button_text":"Ver coleção","eyebrow":""},{"title":"Roupas","image":"","link":"/busca","description":"","reference":"Loja","mobile_image":"","alt":"Roupas","button_text":"Ver coleção","eyebrow":""},{"title":"Coleções","image":"","link":"/colecoes","description":"","reference":"Loja","mobile_image":"","alt":"Coleções","button_text":"Ver coleção","eyebrow":""},{"title":"Outlet","image":"","link":"/promocao","description":"","reference":"Loja","mobile_image":"","alt":"Outlet","button_text":"Ver coleção","eyebrow":""},{"title":"Nossa história","image":"","link":"/p/sobre-nos","description":"","reference":"Sobre","mobile_image":"","alt":"Nossa história","button_text":"Ver coleção","eyebrow":""},{"title":"Trabalhe com a gente","image":"","link":"/trabalhe-conosco","description":"","reference":"Sobre","mobile_image":"","alt":"Trabalhe com a gente","button_text":"Ver coleção","eyebrow":""},{"title":"Fale conosco","image":"","link":"/p/fale-conosco","description":"","reference":"Sobre","mobile_image":"","alt":"Fale conosco","button_text":"Ver coleção","eyebrow":""},{"title":"Trocas e devoluções","image":"","link":"/p/trocas","description":"","reference":"Ajuda","mobile_image":"","alt":"Trocas e devoluções","button_text":"Ver coleção","eyebrow":""},{"title":"Meus pedidos","image":"","link":"/conta/pedidos","description":"","reference":"Ajuda","mobile_image":"","alt":"Meus pedidos","button_text":"Ver coleção","eyebrow":""},{"title":"Cuidados com a peça","image":"","link":"/p/como-lavar","description":"","reference":"Ajuda","mobile_image":"","alt":"Cuidados com a peça","button_text":"Ver coleção","eyebrow":""},{"title":"Privacidade","image":"","link":"/p/privacidade","description":"","reference":"Ajuda","mobile_image":"","alt":"Privacidade","button_text":"Ver coleção","eyebrow":""}]') on conflict(key) do nothing;
commit;
