'use client';
import { useCallback, useEffect, useState } from 'react';
import { Plus, X, Search, Pencil, ArrowUpRight, Package } from 'lucide-react';
import Link from 'next/link';
import { formatPrice } from '@/lib/utils';
import OrderActions from './OrderActions';
import OrderDetails from './OrderDetails';
import ImageUpload from './ImageUpload';
import * as Dialog from '@radix-ui/react-dialog';

type Row=Record<string,unknown> & {id:string;name?:string;slug?:string;is_active?:boolean};
type Variant={size:string;color:string;hex:string;stock:number;sku?:string};
const labels:Record<string,string>={products:'Produtos',categories:'Categorias',collections:'Coleções',creators:'Criadores',featured_categories:'Destaques da página inicial',profiles:'Clientes',orders:'Pedidos',contact_messages:'Atendimento',newsletter_subscribers:'Newsletter'};
const emptyProduct={name:'',slug:'',description:'',price:0,original_price:null,images:[],category_id:'',collection_id:null,is_active:false,is_new:false,is_featured:false};
async function api(resource:string,method='GET',body?:unknown){const r=await fetch('/api/admin/'+resource,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw new Error(b.error?.message||'Não foi possível concluir. Tente novamente.');return b.data;}
export default function AdminManager({resource}:{resource:string}) {
 const [rows,setRows]=useState<Row[]>([]);const [search,setSearch]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [editing,setEditing]=useState<Record<string,unknown>|null>(null);const [variants,setVariants]=useState<Variant[]>([]);const [categories,setCategories]=useState<Row[]>([]);const [collections,setCollections]=useState<Row[]>([]);const [notice,setNotice]=useState('');
 const editable=['products','categories','collections','creators','featured_categories'].includes(resource);
 const load=useCallback(async()=>{setError('');setLoading(true);try{setRows(await api(resource));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[resource]);
 useEffect(()=>{void load();if(resource==='products'){api('categories').then(setCategories).catch(()=>{});api('collections').then(setCollections).catch(()=>{});}},[resource,load]);
 const filtered=rows.filter(r=>Object.values(r).filter(v=>typeof v==='string').join(' ').toLowerCase().includes(search.toLowerCase()));
 function edit(row?:Row){setError('');if(resource==='products'){setEditing(row?{...row}:{...emptyProduct});setVariants(row?(row.product_variants as Variant[]).map(v=>({...v,hex:(row.product_colors as {name:string;hex:string}[]).find(c=>c.name===v.color)?.hex||'#000000'})):[{size:'M',color:'Preto',hex:'#000000',stock:0}]);}else{setEditing(row?{...row}:{name:'',slug:'',description:'',image:'',is_active:true,...(resource==='featured_categories'?{title:'',image_url:'',link_url:'/busca',button_text:'Explorar',position:0}:{})});}}
 const field=(key:string,value:unknown)=>setEditing(p=>({...p,[key]:value}));
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(resource,'POST',{...editing,...(resource==='products'?{variants}:{})});setEditing(null);setNotice('Alterações salvas no banco.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function patch(row:Row,values:Record<string,unknown>){setBusy(true);setError('');try{await api(resource,'PATCH',{id:row.id,...values});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function input(key:string,label:string,type='text',required=false){return <label className="admin-field" key={key}>{label}<input required={required} type={type} value={String(editing?.[key]??'')} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} onChange={e=>field(key,type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/></label>;}
 return <div><div className="flex flex-wrap justify-between gap-4 mb-8"><div><p className="eyebrow">Gestão da loja</p><h1 className="text-3xl">{labels[resource]}</h1><p className="text-sm text-gray-500 mt-2">{rows.length} registros no banco</p></div>{editable&&<button className="btn-primary self-center" onClick={()=>edit()}><Plus size={17}/>Adicionar</button>}</div>{error&&<p role="alert" className="bg-gray-50 text-gray-800 p-4 mb-5">{error}</p>}{notice&&<p role="status" className="bg-gray-50 text-gray-800 p-4 mb-5">{notice}</p>}<label className="flex items-center gap-3 bg-white border p-3 mb-5"><Search size={18}/><input aria-label="Pesquisar registros" placeholder="Pesquisar..." className="w-full outline-none" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 {loading?<p role="status" className="py-10">Carregando registros...</p>:!filtered.length?<div className="bg-white border p-14 text-center"><Package className="mx-auto text-gray-400 mb-5"/><h2 className="text-xl">Nenhum registro encontrado.</h2><p className="text-sm text-gray-500 mt-3">Os dados cadastrados aparecerão aqui.</p></div>:<div className="bg-white border divide-y">{filtered.map(row=><div key={row.id} className="p-5 flex flex-wrap items-center gap-5"><div className="min-w-0 flex-1"><h2 className="font-semibold text-sm">{String(row.name||row.title||row.order_number||row.email||row.subject||row.id)}</h2><p className="text-xs text-gray-500 mt-1">{String(row.slug||row.email||row.created_at||'')}</p>{resource==='products'&&<p className="mt-2 text-sm">{formatPrice(Number(row.price))} · {String(row.stock)} unidades · {row.is_active?'Visível':'Oculto'}</p>}{resource==='orders'&&<><OrderDetails row={row}/><OrderActions order={{id:row.id,status:String(row.status),payment_status:String(row.payment_status),tracking_code:String(row.tracking_code||'')}} onSaved={load}/></>}{resource==='contact_messages'&&<div className="mt-3"><p className="text-sm font-medium">{String(row.subject)}</p><p className="text-sm whitespace-pre-wrap my-3">{String(row.message)}</p><select aria-label="Status do atendimento" value={String(row.status)} onChange={e=>patch(row,{status:e.target.value})} className="border p-2 text-sm"><option value="NEW">Novo</option><option value="READ">Em atendimento</option><option value="RESOLVED">Resolvido</option></select></div>}</div>{resource==='products'&&<Link href={'/produto/'+row.slug} aria-label="Ver produto na loja"><ArrowUpRight size={20}/></Link>}{editable&&<button aria-label={'Editar '+String(row.name||row.title)} className="p-3 border hover:bg-gray-50" onClick={()=>edit(row)}><Pencil size={16}/></button>}{['products','collections'].includes(resource)&&<button disabled={busy} className="border px-4 py-3 text-xs" onClick={()=>patch(row,{is_active:!row.is_active})}>{row.is_active?'Ocultar':'Publicar'}</button>}</div>)}</div>}
 {editing&&<Dialog.Root open onOpenChange={open=>{if(!open&&!busy)setEditing(null);}}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[90] bg-black/40"/><Dialog.Content aria-describedby={undefined} className="fixed right-0 top-0 z-[91] bg-white w-full max-w-3xl h-dvh overflow-y-auto p-6 lg:p-10"><div className="flex justify-between mb-8"><Dialog.Title className="text-2xl">{editing.id?'Editar':'Novo cadastro'}</Dialog.Title><button aria-label="Fechar formulário" onClick={()=>setEditing(null)}><X/></button></div>{error&&<p role="alert" className="text-gray-700 mb-5">{error}</p>}<form onSubmit={save} className="space-y-5">{resource==='featured_categories'?<>{input('title','Título','text',true)}{input('image_url','URL da imagem','url',true)}{input('link_url','Página de destino','text',true)}{input('button_text','Texto do botão','text',true)}{input('position','Posição','number')}</>:<>{input('name','Nome','text',true)}{input('slug','Endereço amigável (slug)','text',true)}<label className="admin-field">Descrição<textarea required={resource==='products'} rows={4} value={String(editing.description||'')} onChange={e=>field('description',e.target.value)}/></label></>}
 {resource==='products'?<><div className="grid grid-cols-2 gap-4">{input('price','Preço (R$)','number',true)}{input('original_price','Preço anterior (opcional)','number')}</div><div className="grid grid-cols-2 gap-4"><label className="admin-field">Categoria<select required value={String(editing.category_id||'')} onChange={e=>field('category_id',e.target.value)}><option value="">Selecione</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="admin-field">Coleção<select value={String(editing.collection_id||'')} onChange={e=>field('collection_id',e.target.value||null)}><option value="">Sem coleção</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><ImageUpload disabled={(editing.images as string[]).length>=10} onUploaded={url=>setEditing(current=>current?{...current,images:[...(current.images as string[]),url].slice(0,10)}:null)}/><label className="admin-field">Imagens (uma URL HTTPS por linha)<textarea rows={3} required value={(editing.images as string[]).join('\n')} onChange={e=>field('images',e.target.value.split('\n').filter(Boolean))}/></label><div className="flex flex-wrap gap-5">{[['is_active','Visível na loja'],['is_new','Lançamento'],['is_featured','Destaque']].map(([k,l])=><label key={k} className="text-sm flex gap-2"><input type="checkbox" checked={!!editing[k]} onChange={e=>field(k,e.target.checked)}/>{l}</label>)}</div><div className="border-t pt-5"><h3 className="font-semibold mb-2">Tamanhos, cores e estoque</h3><p className="text-xs text-gray-500 mb-4">Informe o estoque real de cada combinação. O total é calculado automaticamente.</p>{variants.map((v,i)=><div key={i} className="grid grid-cols-[1fr_1fr_50px_75px_30px] gap-2 mb-3"><input aria-label="Tamanho" placeholder="M" required className="border p-2 min-w-0" value={v.size} onChange={e=>setVariants(vs=>vs.map((x,n)=>n===i?{...x,size:e.target.value}:x))}/><input aria-label="Nome da cor" required className="border p-2 min-w-0" value={v.color} onChange={e=>setVariants(vs=>vs.map((x,n)=>n===i?{...x,color:e.target.value}:x))}/><input aria-label="Cor" type="color" value={v.hex} onChange={e=>setVariants(vs=>vs.map((x,n)=>n===i?{...x,hex:e.target.value}:x))}/><input aria-label="Estoque" type="number" min="0" required className="border p-2 min-w-0" value={v.stock} onChange={e=>setVariants(vs=>vs.map((x,n)=>n===i?{...x,stock:Number(e.target.value)}:x))}/><button type="button" aria-label="Remover variação" onClick={()=>setVariants(vs=>vs.filter((_,n)=>n!==i))}><X size={16}/></button></div>)}<button type="button" className="text-link" onClick={()=>setVariants(v=>[...v,{size:'',color:'',hex:'#000000',stock:0}])}>Adicionar variação</button></div></>:resource!=='featured_categories'&&input('image','URL da imagem (opcional)','url')}
 <div className="flex gap-3 pt-5"><button disabled={busy} className="btn-primary" type="submit">{busy?'Salvando...':'Salvar alterações'}</button><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Cancelar</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>}</div>;
}

