'use client';
import {useState} from 'react';
const labels:Record<string,string>={PENDING:'Aguardando pagamento',CONFIRMED:'Confirmado',PROCESSING:'Em preparação',SHIPPED:'Enviado',DELIVERED:'Entregue',CANCELLED:'Cancelado'};
const transitions:Record<string,string[]>={PENDING:['CONFIRMED','CANCELLED'],CONFIRMED:['PROCESSING','CANCELLED'],PROCESSING:['SHIPPED','CANCELLED'],SHIPPED:['DELIVERED'],DELIVERED:[],CANCELLED:[]};
export default function OrderActions({order,onSaved}:{order:{id:string;status:string;payment_status:string;tracking_code?:string};onSaved:()=>Promise<void>}){
 const [target,setTarget]=useState('');const [tracking,setTracking]=useState(order.tracking_code||'');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:order.id,status:target,tracking_code:tracking,note})});const b=await r.json();if(!r.ok)throw new Error(b.error?.message||'Não foi possível atualizar o pedido.');setTarget('');setNote('');await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const available=(transitions[order.status]||[]).filter(s=>s==='CANCELLED'?['PENDING','FAILED','REFUNDED'].includes(order.payment_status):order.payment_status==='PAID');
 return <div className="mt-5 border-t pt-4"><p className="text-sm font-medium mb-3">{labels[order.status]||order.status}</p>{available.length?<form onSubmit={save} className="space-y-3 max-w-lg"><label className="admin-field">Próxima etapa<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Selecione</option>{available.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>{target==='SHIPPED'&&<label className="admin-field">Código de rastreio<input required maxLength={100} value={tracking} onChange={e=>setTracking(e.target.value)}/></label>}{target&&<><label className="admin-field">Observação (opcional)<textarea maxLength={1000} rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label>{target==='CANCELLED'&&<p className="text-xs text-gray-600">O cancelamento devolverá as unidades ao estoque. Esta ação não solicita reembolso ao gateway.</p>}<button disabled={busy} className="btn-primary text-xs" type="submit">{busy?'Atualizando...':'Confirmar alteração'}</button></>}</form>:<p className="text-xs text-gray-500">{['DELIVERED','CANCELLED'].includes(order.status)?'Pedido finalizado.':'A próxima etapa depende da confirmação do pagamento ou reembolso.'}</p>}{error&&<p role="alert" className="text-sm mt-3">{error}</p>}</div>;
}
